name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
  test:
    needs: lint
    strategy:
      matrix:
        node_versions: [10, 12, 14]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_versions }}
      - name: Install mpd
        run: sudo apt install mpd
      - name: Install node modules
        run: npm install
      - name: Run Tests
        run: npm test
